services:
  - type: web
    name: jokers-edge
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --workers 2 --threads 4 --timeout 180
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: OPENWEATHER_API_KEY
        sync: false
      - key: SCAN_GAME_WORKERS
        value: "4"
      - key: SCAN_API_WORKERS
        value: "4"
      - key: PYTHON_VERSION
        value: 3.11.4
