import { type PickData } from "./PickCard";

export const MOCK_PICKS: PickData[] = [
  {
    id: "1",
    tier: "STRONG PLAY",
    coverPct: 72.1,
    compositeScore: 14,
    awayTeam: "LAL",
    homeTeam: "BOS",
    gameTime: "7:30 PM EST",
    slotType: "Vegas Slot",
    actionString: "Take Lakers +6.5 or better — don't take past +5",
    spreadLine: "Lakers +6.5",
    factors: [
      { label: "Line ↗", icon: "📈", points: 3 },
      { label: "B2B", icon: "🔄", points: 2 },
      { label: "Sharp", icon: "🎯", points: 5 },
      { label: "Trell", icon: "⚡", points: 5, unvalidated: true },
    ],
    moneyline: "Lakers +220",
    hasUnvalidated: true,
  },
  {
    id: "2",
    tier: "CONFIDENT",
    coverPct: 69.8,
    compositeScore: 11,
    awayTeam: "CGY",
    homeTeam: "EDM",
    gameTime: "9:00 PM EST",
    slotType: "Public",
    actionString: "Take Oilers ML — home ice advantage plus fatigue edge",
    spreadLine: "Oilers -1.5",
    factors: [
      { label: "Home", icon: "🏠", points: 3 },
      { label: "Rest", icon: "😴", points: 4 },
      { label: "Goalie", icon: "🥅", points: 4 },
    ],
    moneyline: "Oilers -150",
  },
  {
    id: "3",
    tier: "LEAN",
    coverPct: 64.3,
    compositeScore: 8,
    awayTeam: "PHX",
    homeTeam: "DEN",
    gameTime: "8:00 PM EST",
    slotType: "Vegas Slot",
    actionString: "Nuggets -4.5 at home — altitude factor in play",
    spreadLine: "Nuggets -4.5",
    factors: [
      { label: "Altitude", icon: "🏔️", points: 3 },
      { label: "H2H", icon: "📊", points: 2 },
      { label: "Pace", icon: "⏱️", points: 3 },
    ],
  },
  {
    id: "4",
    tier: "MONITOR",
    coverPct: 61.2,
    compositeScore: 6,
    awayTeam: "CHI",
    homeTeam: "MIL",
    gameTime: "8:30 PM EST",
    slotType: "Public",
    actionString: "Bucks -8.5 — large spread but Bulls depleted",
    spreadLine: "Bucks -8.5",
    factors: [
      { label: "Injuries", icon: "🏥", points: 4 },
      { label: "Public", icon: "📢", points: -2, unvalidated: true },
      { label: "Spread", icon: "📏", points: 2 },
    ],
    hasUnvalidated: true,
  },
  {
    id: "5",
    tier: "CONFIDENT",
    coverPct: 70.5,
    compositeScore: 12,
    awayTeam: "MIN",
    homeTeam: "DAL",
    gameTime: "7:00 PM EST",
    slotType: "Vegas Slot",
    actionString: "Take Wolves +3 — sharp money moving the line",
    spreadLine: "Wolves +3",
    factors: [
      { label: "Sharp", icon: "🎯", points: 5 },
      { label: "Line ↗", icon: "📈", points: 3 },
      { label: "Defense", icon: "🛡️", points: 4 },
    ],
    moneyline: "Wolves +130",
  },
];
